export const INDEXED_DB_NAME = 'redis-fans-db';
export const INDEXED_DB_VERSION = 1;
export const MESSAGE_DURATION = 3000;
export const LUA_OUTPUT_NUMS_MAX = 10;
export const LIST_TO_DELTE_VALUE = '__LIST_TO_DELTE_VALUE__';

export const DIMENSION_APPHEADER_HEIGHT = 36;
export const DIMENSION_APPFOOTER_HEIGHT = 24;
export const DIMENSION_APPLEFTSIDEBAR_WIDTH = 350;
export const DIMENSION_APPLEFTSIDEBAR_WIDTH_MINSIZE = 350;
export const DIMENSION_APPLEFTSIDEBAR_WIDTH_MAXSIZE = 500;
export const DIMENSION_APPLEFTSIDEBAR_CLOSED_WIDTH = 50;

export const DIMENSION_ROWS_WIDTH_MINSIZE = 300;
export const DIMENSION_ROWS_WIDTH_MAXSIZE = 400;

export const DIMENSION_LUAEDITOR_CLOSED_DRAWER_WIDTH = 0;
export const DIMENSION_LUAEDITOR_OPENED_DRAWER_WIDTH = 300;
export const DIMENSION_LUAEDITOR_CLOSED_RESULT_SIZE = 41;
export const DIMENSION_LUAEDITOR_OPENED_RESULT_SIZE = 400;

export const DIMENSION_OBJECT_LIST_AVATARWIDTH = 24;
export const DIMENSION_OBJECT_LIST_AVATARHEIGHT = 24;

export const DIMENSION_APPSESSIONFOOTER_HEIGHT = 4;
export const DIMENSION_APPRESIZER_HANDLER_SIZE = 4;

export const REACTDND_ITEMTYPE_SESSIONTAB = 'session-tab';
export const REACTDND_ITEMTYPE_TAB = 'tab';

export const DEFAULT_SCAN_COUNT = 1000;
export const DEFAULT_LRANGE_COUNT = 200;
export const DEFAULT_HSCAN_COUNT = 200;
export const DEFAULT_SSCAN_COUNT = 200;
export const DEFAULT_ZSCAN_COUNT = 200;

export const DEFAULT_MATCH_STR = '*';
